version: "3"

services:
  jupyter:
    container_name: client-jupyter
    image: client-jupyter
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/notebooks
    environment:
      - GRANT_SUDO=yes
    user: root

volumes:
  notebooks:
